# Generated by Django 3.2.7 on 2021-11-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.CharField(default=5000, max_length=150),
            preserve_default=False,
        ),
    ]
