# Generated by Django 3.2.7 on 2021-11-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_article_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
    ]
