# Generated by Django 3.2.7 on 2021-11-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_auto_20211101_0400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calm',
        ),
    ]
