# Generated by Django 3.2.7 on 2021-11-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.CharField(default=3000, max_length=100),
            preserve_default=False,
        ),
    ]
