# Generated by Django 3.2.7 on 2021-11-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0022_commande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande']},
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='data_commande',
            new_name='date_commande',
        ),
    ]
