# Generated by Django 3.2.7 on 2021-11-02 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0023_auto_20211102_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Article',
            field=models.ForeignKey(default=34433, on_delete=django.db.models.deletion.CASCADE, to='bookstore.article'),
            preserve_default=False,
        ),
    ]
