# Generated by Django 3.2.7 on 2021-11-03 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0025_remove_commande_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='numcart',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='numerophone',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='payerpar',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('application', 'Application')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('extra_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatednotification', to='bookstore.order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='bookstore.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
