# Generated by Django 3.2.7 on 2021-11-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0032_commande_tit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='tit',
        ),
    ]
