# Generated by Django 3.2.7 on 2021-11-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0033_remove_commande_tit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc_ar',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
