# Generated by Django 3.2.7 on 2021-11-06 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0034_auto_20211106_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='tit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(default='anything'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc_ar',
            field=models.TextField(default='anything'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(default='anything', max_length=50),
        ),
    ]
