# Generated by Django 3.2.7 on 2021-11-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0035_auto_20211106_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='tit',
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc_ar',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(default='', max_length=50),
        ),
    ]
