# Generated by Django 3.2.7 on 2021-11-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0036_auto_20211106_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc_ar',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=50),
        ),
    ]
